[project]
name = "dep"
version = "4.1.0"
requires-python = ">=3.11"
dependencies = [
    "pygments<2.1.1",
]

[project.scripts]
dep = "dep:hello_dep"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  ".venv*",
]
