[project]
name = "baz"
version = "1.1.0"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
baz = "baz:hello_baz"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
  ".venv*",
]
