[project]
name = "bar"
version = "1.2.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
bar = "bar:hello_bar"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
