[project]
name = "foo"
version = "1.3.0"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
foo = "foo:hello_foo"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
