# Install dependencies and run tests on push and on pull request

name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        #os: ["ubuntu-latest", "windows-latest"]
        os: ["ubuntu-latest"]
        python-version: ["3.13",]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out the project
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.4"
        python-version: ${{ matrix.python-version }}
        enable-cache: true
        cache-dependency-glob: "uv.lock"          

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build the test data
      run: uv run scripts/build-test-data.py

    - name: Run tests
      run: uv run pytest
